authors:
- Ansible
dependencies: {}
description: Bulk test collection tnsb164e5.tce0cd2806 (based on ansible.utils)
license:
- GPL-2.0-or-later
name: tce0cd2806
namespace: tnsb164e5
readme: README.md
repository: https://github.com/test/tnsb164e5.tce0cd2806
tags:
- networking
version: 6.0.2
